### ISSUE TITLE
Hvordan sette ukm.dev, og prod-mode i .env-filen på en god måte?

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMDesignSymfony5#2]

**Comment by AsgeirSH** [comment]
Vi burde vel bruke environment-innstillingene til Apache / CPanel i stedet for .env. .env er anbefalt mest i devmiljø så vidt jeg har funnet ut.

**Comment by mariusmandal** [comment]
Lagt til i feature req system
